---
{{ if .Env.TRUSTED_HOSTS }}
:trusted_hosts:
{{ range split .Env.TRUSTED_HOSTS "," -}}
  - {{.}}
{{ end }}
{{ else }}
:trusted_hosts: []
{{ end }}
:foreman_url: {{ .Env.FOREMAN_URL }}
:daemon: false
:bind_host: '*'
:http_port: 8000
:log_file: STDOUT
:log_level: INFO
